### WINDOWS AND WORKSPACES ###

# 1. Ignore maximize requests from all apps.
windowrulev2 = suppressevent maximize, class:.*

# 2. Fix some dragging issues with XWayland
windowrulev2 = nofocus, class:^$, title:^$, xwayland:1, floating:1, fullscreen:0, pinned:0

# 3. Hyprland-run windowrule
windowrulev2 = float, class:^(hyprland-run)$
windowrulev2 = move 20 100%-120, class:^(hyprland-run)$
